vagrantfile:
  vm:
    provider:
      local:
        machines:
          machine_box:
            id: silkrock-new.dev
            hostname: silkrock-new.dev
            network:
              private_network: 192.168.4.119
nginx:
  vhosts:
    development_host:
      server_name: silkrock-new.dev
      server_aliases:
        - www.silkrock-new.dev

mariadb:
  users:
    db_user_1:
        name: silkrock-new.dev
        password: '123'
  databases:
      db_1:
          name: silkrock-new.dev
  grants:
      grants_1:
          user: silkrock-new.dev